/**
 * MCP GATE - red until YOU build a server of your own in mcp/my-server.ts.
 * Do not edit this file.
 *
 * A real MCP client spawns your server exactly the way .mcp.json does
 * ( `pnpm --silent exec tsx mcp/my-server.ts` ), speaks the protocol to it
 * over stdio - initialize, tools/list, tools/call - and asserts what the
 * assignment requires. No model is involved: this suite is deterministic.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import path from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { createServer as createExampleServer } from "../../mcp/example-server.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";

type Tool = Awaited<ReturnType<Client["listTools"]>>["tools"][number];
type JsonSchema = {
  type?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  enum?: unknown[];
  minimum?: number;
  minLength?: number;
  items?: JsonSchema;
};

const root = path.resolve(import.meta.dirname, "..", "..");

/** The example's tools, read from the example itself - so a rename of ITS tools cannot fool the gate. */
async function exampleTools(): Promise<Tool[]> {
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  await createExampleServer().connect(serverTransport);
  const client = new Client({ name: "gate-example-reader", version: "1.0.0" });
  await client.connect(clientTransport);
  const { tools } = await client.listTools();
  await client.close();
  return tools;
}

/** A tool's input SHAPE: its sorted property names. Two tools with the same shape are "the same tool renamed". */
function shapeOf(tool: Tool): string {
  return Object.keys(tool.inputSchema.properties ?? {}).sort().join(",");
}

/** Build one plausible argument for a JSON-schema property, honouring enum / minimum / minLength. */
function sampleValue(schema: JsonSchema): unknown {
  if (schema.enum && schema.enum.length > 0) return schema.enum[0];
  switch (schema.type) {
    case "integer":
    case "number":
      return Math.max(schema.minimum ?? 1, 1);
    case "boolean":
      return true;
    case "array":
      return schema.items ? [sampleValue(schema.items)] : [];
    case "object":
      return sampleArguments(schema);
    default:
      return "example".padEnd(schema.minLength ?? 0, "x");
  }
}

function sampleArguments(schema: JsonSchema): Record<string, unknown> {
  const args: Record<string, unknown> = {};
  for (const name of schema.required ?? []) {
    const prop = schema.properties?.[name];
    args[name] = prop ? sampleValue(prop) : "example";
  }
  return args;
}

let client: Client;
let transport: StdioClientTransport;
let tools: Tool[] = [];
let listError: unknown;

beforeAll(async () => {
  transport = new StdioClientTransport({
    command: "pnpm",
    args: ["--silent", "exec", "tsx", "mcp/my-server.ts"],
    cwd: root,
    stderr: "pipe",
  });
  client = new Client({ name: "gate-client", version: "1.0.0" });
  await client.connect(transport);
  try {
    tools = (await client.listTools()).tools;
  } catch (err) {
    // an McpServer with nothing registered answers tools/list with "method not found"
    listError = err;
    tools = [];
  }
}, 60_000);

afterAll(async () => {
  await client?.close();
});

describe("my-tools MCP server (mcp/my-server.ts)", () => {
  it("initialises over stdio as a server that is not the example", () => {
    const info = client.getServerVersion();
    expect(info?.name, "server name").toBeDefined();
    expect(info?.name).not.toBe("course-tools");
  });

  it("exposes at least one tool", () => {
    expect(tools.length, `no tools listed${listError ? ` (${String(listError)})` : ""}`).toBeGreaterThan(0);
  });

  it("every tool differs from the example's tools in NAME and in INPUT SHAPE", async () => {
    const examples = await exampleTools();
    const exampleNames = new Set(examples.map((t) => t.name));
    const exampleShapes = new Set(examples.map(shapeOf));
    expect(tools.length).toBeGreaterThan(0);
    for (const tool of tools) {
      expect(exampleNames.has(tool.name), `tool "${tool.name}" reuses an example tool's name`).toBe(false);
      expect(exampleShapes.has(shapeOf(tool)), `tool "${tool.name}" has an example tool's input shape (${shapeOf(tool)})`).toBe(false);
    }
  });

  it("at least one tool declares a REQUIRED, typed input", () => {
    const withRequired = tools.filter((t) => {
      const schema = t.inputSchema as JsonSchema;
      return (schema.required ?? []).some((name) => schema.properties?.[name]?.type !== undefined);
    });
    expect(withRequired.length, "no tool has a required input with a declared type").toBeGreaterThan(0);
  });

  it("answers a call to a tool with a required input, built from its own schema", async () => {
    const tool = tools.find((t) => ((t.inputSchema as JsonSchema).required ?? []).length > 0);
    expect(tool, "no tool with a required input to call").toBeDefined();
    const result = await client.callTool({
      name: tool!.name,
      arguments: sampleArguments(tool!.inputSchema as JsonSchema),
    });
    expect(result.isError, `tool "${tool!.name}" returned an error for arguments built from its own schema`).not.toBe(true);
    const content = result.content as unknown[];
    expect(content.length, "empty result").toBeGreaterThan(0);
  }, 30_000);
});
