/**
 * OUTCOME GATE - red until your orchestration generates target/version-toolkit.ts
 * from requirements/version_toolkit_requirements.md. Do not edit this file.
 */
import { describe, expect, it } from "vitest";
import { bumpVersion, VersionError, type BumpPart } from "../../../target/version-toolkit.js";

describe("bumpVersion", () => {
  it("bumps the named part and zeroes everything below it", () => {
    expect(bumpVersion({ major: 1, minor: 4, patch: 2 }, "major")).toEqual({ major: 2, minor: 0, patch: 0 });
    expect(bumpVersion({ major: 1, minor: 4, patch: 2 }, "minor")).toEqual({ major: 1, minor: 5, patch: 0 });
    expect(bumpVersion({ major: 1, minor: 4, patch: 2 }, "patch")).toEqual({ major: 1, minor: 4, patch: 3 });
  });

  it("returns a new object and leaves the input untouched", () => {
    const original = { major: 3, minor: 1, patch: 0 };
    const bumped = bumpVersion(original, "minor");
    expect(bumped).not.toBe(original);
    expect(original).toEqual({ major: 3, minor: 1, patch: 0 });
  });

  it("throws VersionError on an unknown part", () => {
    expect(() => bumpVersion({ major: 1, minor: 0, patch: 0 }, "build" as BumpPart)).toThrow(VersionError);
    expect(() => bumpVersion({ major: 1, minor: 0, patch: 0 }, "build" as BumpPart)).toThrow(/build/);
  });
});
