/**
 * OUTCOME GATE - red until your orchestration generates target/version-toolkit.ts
 * from requirements/version_toolkit_requirements.md. Do not edit this file.
 */
import { describe, expect, it } from "vitest";
import { compareVersions, type Version } from "../../../target/version-toolkit.js";

const v = (major: number, minor: number, patch: number): Version => ({ major, minor, patch });

describe("compareVersions", () => {
  it("returns 0 for equal versions", () => {
    expect(compareVersions(v(1, 2, 3), v(1, 2, 3))).toBe(0);
  });

  it("orders by major, then minor, then patch", () => {
    expect(compareVersions(v(2, 0, 0), v(1, 9, 9))).toBe(1);
    expect(compareVersions(v(1, 9, 9), v(2, 0, 0))).toBe(-1);
    expect(compareVersions(v(1, 3, 0), v(1, 2, 9))).toBe(1);
    expect(compareVersions(v(1, 2, 4), v(1, 2, 5))).toBe(-1);
  });

  it("compares numerically, not as text", () => {
    expect(compareVersions(v(1, 10, 0), v(1, 9, 0))).toBe(1);
    expect(compareVersions(v(1, 0, 10), v(1, 0, 2))).toBe(1);
  });
});
