/**
 * OUTCOME GATE - red until your orchestration generates target/version-toolkit.ts
 * from requirements/version_toolkit_requirements.md. Do not edit this file.
 */
import { describe, expect, it } from "vitest";
import { formatVersion } from "../../../target/version-toolkit.js";

describe("formatVersion", () => {
  it("renders MAJOR.MINOR.PATCH with no prefix", () => {
    expect(formatVersion({ major: 1, minor: 4, patch: 2 })).toBe("1.4.2");
    expect(formatVersion({ major: 0, minor: 0, patch: 0 })).toBe("0.0.0");
    expect(formatVersion({ major: 12, minor: 0, patch: 7 })).toBe("12.0.7");
  });
});
