/**
 * OUTCOME GATE - red until your orchestration generates target/version-toolkit.ts
 * from requirements/version_toolkit_requirements.md. Do not edit this file.
 */
import { describe, expect, it } from "vitest";
import { parseVersion, VersionError } from "../../../target/version-toolkit.js";

describe("parseVersion", () => {
  it("parses MAJOR.MINOR.PATCH into three numbers", () => {
    expect(parseVersion("1.4.2")).toEqual({ major: 1, minor: 4, patch: 2 });
    expect(parseVersion("0.0.0")).toEqual({ major: 0, minor: 0, patch: 0 });
    expect(parseVersion("10.20.30")).toEqual({ major: 10, minor: 20, patch: 30 });
  });

  it("accepts a single leading v", () => {
    expect(parseVersion("v2.0.1")).toEqual({ major: 2, minor: 0, patch: 1 });
  });

  it("throws VersionError, naming the input, on anything else", () => {
    for (const bad of ["1.2", "1.2.3.4", "1.2.x", "-1.2.3", "01.2.3", " 1.2.3", "1.2.3-beta", "vv1.2.3", ""]) {
      expect(() => parseVersion(bad), bad).toThrow(VersionError);
      expect(() => parseVersion(bad), bad).toThrow(bad.length > 0 ? bad : /./);
    }
  });
});
