/**
 * OUTCOME GATE - red until your orchestration generates target/version-toolkit.ts
 * from requirements/version_toolkit_requirements.md. Do not edit this file.
 */
import { describe, expect, it } from "vitest";
import { satisfiesRange, VersionError, type Version } from "../../../target/version-toolkit.js";

const v = (major: number, minor: number, patch: number): Version => ({ major, minor, patch });

describe("satisfiesRange", () => {
  it("handles each single comparator", () => {
    expect(satisfiesRange(v(1, 2, 0), ">=1.2.0")).toBe(true);
    expect(satisfiesRange(v(1, 1, 9), ">=1.2.0")).toBe(false);
    expect(satisfiesRange(v(1, 2, 1), ">1.2.0")).toBe(true);
    expect(satisfiesRange(v(1, 2, 0), ">1.2.0")).toBe(false);
    expect(satisfiesRange(v(2, 0, 0), "<=2.0.0")).toBe(true);
    expect(satisfiesRange(v(2, 0, 1), "<=2.0.0")).toBe(false);
    expect(satisfiesRange(v(1, 9, 9), "<2.0.0")).toBe(true);
    expect(satisfiesRange(v(2, 0, 0), "<2.0.0")).toBe(false);
    expect(satisfiesRange(v(1, 2, 3), "=1.2.3")).toBe(true);
    expect(satisfiesRange(v(1, 2, 4), "=1.2.3")).toBe(false);
  });

  it("treats a bare version as an exact match", () => {
    expect(satisfiesRange(v(1, 2, 3), "1.2.3")).toBe(true);
    expect(satisfiesRange(v(1, 2, 3), "1.2.4")).toBe(false);
  });

  it("requires every whitespace-separated comparator to hold", () => {
    expect(satisfiesRange(v(1, 5, 0), ">=1.2.0 <2.0.0")).toBe(true);
    expect(satisfiesRange(v(2, 0, 0), ">=1.2.0 <2.0.0")).toBe(false);
    expect(satisfiesRange(v(1, 1, 0), ">=1.2.0 <2.0.0")).toBe(false);
    expect(satisfiesRange(v(1, 5, 0), ">=1.2.0   <2.0.0")).toBe(true);
  });

  it("throws VersionError on an empty or malformed range", () => {
    for (const bad of ["", "   ", ">=", "~1.2.0", ">=1.2", "1.2.0 || 2.0.0", "<>1.2.0"]) {
      expect(() => satisfiesRange(v(1, 2, 0), bad), JSON.stringify(bad)).toThrow(VersionError);
    }
  });
});
